alias update='sudo apt-get update'
alias upgrade='sudo apt-get upgrade'
alias reboot='sudo reboot'
alias install='sudo apt-get install'
alias shutdown='sudo shutdown -h now'

alias renameSim='rm netsim.py && mv netsim.py.1 netsim.py'
alias minEx='cd /home/$USER/mininet/examples'

alias add='git add'
alias commit='git commit -m'
alias pull='git pull'
alias status='git status'
alias push='git push'
alias remoteadd='git remote add origin https://github.com/sadican/ranet'
alias gitc='git add $1 && git commit -m $2 && git remote add origin https://github.com/sadican/$3 && git push'
